  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/sdim_34-89306/pip-req-build-pept7og9
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/sdim_34-89306/pip-req-build-25okmmua
Map:   0%|          | 0/112 [00:00<?, ? examples/s]Map:  50%|█████     | 56/112 [00:00<00:00, 547.47 examples/s]Map: 100%|██████████| 112/112 [00:00<00:00, 486.73 examples/s]Map: 100%|██████████| 112/112 [00:00<00:00, 478.29 examples/s]
Map:   0%|          | 0/29 [00:00<?, ? examples/s]Map: 100%|██████████| 29/29 [00:00<00:00, 445.18 examples/s]
  0%|          | 0/2 [00:00<?, ?it/s] 50%|█████     | 1/2 [00:03<00:03,  3.23s/it]                                              50%|█████     | 1/2 [00:03<00:03,  3.23s/it]100%|██████████| 2/2 [00:05<00:00,  2.84s/it]                                             100%|██████████| 2/2 [00:05<00:00,  2.84s/it]                                             100%|██████████| 2/2 [00:06<00:00,  2.84s/it]100%|██████████| 2/2 [00:06<00:00,  3.12s/it]
Traceback (most recent call last):
  File "/usr/users/sdim/sdim_34/lora-llm/lora_training.py", line 182, in <module>
    model.save_pretrained(local_model_path)
  File "/tmp/sdim_34-89306/venv/lib/python3.10/site-packages/peft/peft_model.py", line 222, in save_pretrained
    raise ValueError(f"Provided path ({save_directory}) should be a directory, not a file")
ValueError: Provided path (/usr/users/sdim/sdim_34/lora-llm/my_local_model) should be a directory, not a file
